//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const USER_DATA = 'USER_DATA';
export const USER_TOKEN_SET = 'USER_TOKEN_SET';

// token verify
export const TOKEN_VERIFY_SUCCESS = 'TOKEN_VERIFY_SUCCESS';
export const TOKEN_VERIFY_FAILED = 'TOKEN_VERIFY_FAILED';
export const TOKEN_VERIFY_FETCH = 'TOKEN_VERIFY_FETCH';


// master customer 
export const MASTER_CUSTOMER_FETCH = "MASTER_CUSTOMER_FETCH";
export const MASTER_CUSTOMER_SUCCESS = "MASTER_CUSTOMER_SUCCESS";
export const MASTER_CUSTOMER_FAILED = "MASTER_CUSTOMER_FAILED";

// global
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';